In [1]:
import numpy as np
def hebbian_learning_rule(input_pat,wt_matrix):
    return wt_matrix+np.outer(input_pat,input_pat)

In [11]:
def perceptron_learning_rule(input_pat,target,wt_vector,lr):
    prediction=np.dot(wt_vector,input_pat)
    error=target-prediction
    return wt_vector+lr*error*input_pat

def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pattern)

# Correlation Learning Rule
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Out Star Learning Rule
def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pattern, input_pattern)


In [12]:
input_pattern=np.array([0.2,0.8,0.5])
target=1;
input_size=3;

hebbian_weights = np.random.rand(input_size, input_size)

perceptron_weights = np.random.rand(input_size)

delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)

print("Hebbian Weights:",hebbian_weights)
print("\nPerceptron Weights:",perceptron_weights)
print("\nDelta Weights:",delta_weights)
print("\nCorrelation Weights:",correlation_weights)
print("\nOut Star Weights:",out_star_weights)

Hebbian Weights: [[0.5593155  0.97395407 0.25531177]
 [0.4335187  0.44096217 0.551466  ]
 [0.28840383 0.23334625 0.68139707]]

Perceptron Weights: [0.33258681 0.93786572 0.26918333]

Delta Weights: [[0.70250527 0.99665144 0.2870254 ]
 [0.26300573 0.06159491 0.30292319]
 [0.49817413 0.914084   0.30282724]]

Correlation Weights: [[0.71183518 0.17620826 0.71290807]
 [0.74386181 0.71433159 0.43517329]
 [0.71248935 0.20065919 0.54692766]]

Out Star Weights: [[0.58291349 0.56713037 0.31442949]
 [0.42540285 0.5940449  0.3425447 ]
 [0.04262027 0.74101964 0.95087762]]


In [14]:
hebbian_weights_updated = hebbian_learning_rule(input_pattern, hebbian_weights)

perceptron_weights_updated = perceptron_learning_rule(input_pattern, target,perceptron_weights, 0.1)

delta_weights_updated = delta_learning_rule(input_pattern, target, delta_weights,learning_rate=0.1)

correlation_weights_updated = correlation_learning_rule(input_pattern, correlation_weights)

out_star_weights_updated = out_star_learning_rule(input_pattern, out_star_weights,learning_rate=0.1)

# Display updated weights
print("Hebbian Updated Weights:", hebbian_weights_updated)
print("\nPerceptron Updated Weights:", perceptron_weights_updated)
print("\nDelta Updated Weights:", delta_weights_updated)
print("\nCorrelation Updated Weights:",correlation_weights_updated)
print("\nOut Star Updated Weights:",out_star_weights_updated)

Hebbian Updated Weights: [[0.5993155  1.13395407 0.35531177]
 [0.5935187  1.08096217 0.951466  ]
 [0.38840383 0.63334625 0.93139707]]

Perceptron Updated Weights: [0.33355878 0.9417536  0.27161325]

Delta Updated Weights: [[0.70087857 0.99014465 0.28295866]
 [0.27793896 0.12132782 0.34025626]
 [0.49852782 0.91549875 0.30371146]]

Correlation Updated Weights: [[0.75183518 0.33620826 0.81290807]
 [0.90386181 1.35433159 0.83517329]
 [0.81248935 0.60065919 0.79692766]]

Out Star Updated Weights: [[0.58691349 0.58313037 0.32442949]
 [0.44140285 0.6580449  0.3825447 ]
 [0.05262027 0.78101964 0.97587762]]
